#!/usr/bin/env python3
# =============================================================================
# 05_supplementary_tables.py
#
# PURPOSE:
#   Assemble all previously computed interaction and compatibility data into
#   a single multi-sheet Excel supplementary file ready for manuscript submission.
#
# SHEETS GENERATED:
#   S1_Genome_Summary     — per-genome compatibility metrics and exchange overview
#   S2_All_Interactions   — all significant pairwise metabolic interactions
#   S3_Pairwise_Summary   — aggregated metrics per producer–consumer pair
#   S4_Metabolite_Summary — per-metabolite exchange statistics across community
#
# INPUT (generated by scripts 03 and 04):
#   - tabla_interacciones_13genomas.csv
#   - compatibility_scores_13genomas.csv
#
# OUTPUT:
#   - supplementary_table_syncom.xlsx
#
# DEPENDENCIES:
#   pip install pandas openpyxl
#
# USAGE:
#   conda activate micom_env
#   python3 05_supplementary_tables.py
#
# AUTHORS: Enrique Pola-Sánchez, Jose Manuel Villalobos-Escobedo
# PROJECT: SynCom design from Mexican fermented beverages
# =============================================================================

import pandas as pd
import numpy as np

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------
BASE    = "/Users/manuelve/Documents/GEMs/MAGs_new"
GENOMES = [f"genome{i}" for i in list(range(1, 10)) + list(range(10, 14))]

# ------------------------------------------------------------
# Load input data
# ------------------------------------------------------------
df        = pd.read_csv(f"{BASE}/tabla_interacciones_13genomas.csv")
df_scores = pd.read_csv(f"{BASE}/compatibility_scores_13genomas.csv", index_col=0)

# ============================================================
# SHEET S1: Per-genome summary
# ============================================================
rows_summary = []
for g in GENOMES:
    prod_df = df[df["producer"] == g]
    cons_df = df[df["consumer"] == g]

    # Guard against genomes not present in df_scores
    if g not in df_scores.index:
        print(f"  [WARN] {g} not found in compatibility_scores — skipping")
        continue

    rows_summary.append({
        "Genome":                        g,
        "Compatibility Score":           round(df_scores.loc[g, "compatibility_score"], 4),
        "Compatible (threshold=0.35)":   df_scores.loc[g, "compatible"],
        "Growth Rate (h⁻¹)":             round(df_scores.loc[g, "growth_rate"], 4),
        "Exported Flux (total mmol/gDW/h)": round(df_scores.loc[g, "exported_flux"], 4),
        "Imported Flux (total mmol/gDW/h)": round(df_scores.loc[g, "imported_flux"], 4),
        # Positive = net donor; negative = net receiver
        "Net Contribution (mmol/gDW/h)": round(df_scores.loc[g, "net_contribution"], 4),
        "Connectivity (in+out partners)":int(df_scores.loc[g, "connectivity"]),
        "Metabolites Exported (unique)": prod_df["metabolite_id"].nunique(),
        "Metabolites Imported (unique)": cons_df["metabolite_id"].nunique(),
        "Producer Partners (unique)":    prod_df["consumer"].nunique(),
        "Consumer Partners (unique)":    cons_df["producer"].nunique(),
        "Top Exported Metabolite":       (
            prod_df.sort_values("exchange_flux", ascending=False)["metabolite_name"].iloc[0]
            if len(prod_df) > 0 else "—"
        ),
        "Top Imported Metabolite":       (
            cons_df.sort_values("exchange_flux", ascending=False)["metabolite_name"].iloc[0]
            if len(cons_df) > 0 else "—"
        ),
        "Exported Categories":           (
            "|".join(sorted(prod_df["category"].unique()))
            if len(prod_df) > 0 else "—"
        ),
        "Imported Categories":           (
            "|".join(sorted(cons_df["category"].unique()))
            if len(cons_df) > 0 else "—"
        ),
    })

df_summary = (pd.DataFrame(rows_summary)
                .sort_values("Compatibility Score", ascending=False))

# ============================================================
# SHEET S2: All significant pairwise interactions
# ============================================================
df_interactions = df.copy().rename(columns={
    "producer":         "Producer",
    "consumer":         "Consumer",
    "metabolite_id":    "Metabolite ID (BiGG)",
    "metabolite_name":  "Metabolite Name",
    "category":         "Category",
    "flux_producer":    "Flux Producer (mmol/gDW/h)",
    "flux_consumer":    "Flux Consumer (mmol/gDW/h)",
    "exchange_flux":    "Exchange Flux (avg mmol/gDW/h)",
    # NOTE: significance_pct is a relative flux metric, NOT a statistical p-value.
    # It represents the fraction of the producer's total metabolic flux
    # dedicated to exporting this particular metabolite.
    "significance_pct": "Relative Flux (%)",
})

# ============================================================
# SHEET S3: Aggregated producer–consumer pair summary
# ============================================================
pair_rows = []
for (prod, cons), group in df.groupby(["producer", "consumer"]):
    pair_rows.append({
        "Producer":                   prod,
        "Consumer":                   cons,
        "Total Exchange Flux":        round(group["exchange_flux"].sum(), 4),
        "N Interactions":             len(group),
        "Unique Metabolites":         group["metabolite_id"].nunique(),
        "Categories":                 "|".join(sorted(group["category"].unique())),
        "Top Metabolite":             (
            group.sort_values("exchange_flux", ascending=False)["metabolite_name"].iloc[0]
        ),
        "Max Relative Flux (%)":      round(group["significance_pct"].max(), 4),
        "Amino acids (#)":            len(group[group["category"] == "Amino acids"]),
        "Carbon sources (#)":         len(group[group["category"] == "Carbon sources"]),
        "Cofactors (#)":              len(group[group["category"] == "Cofactors"]),
        "Nucleotides (#)":            len(group[group["category"] == "Nucleotides"]),
        "Ions (#)":                   len(group[group["category"] == "Ions"]),
        "Other (#)":                  len(group[group["category"] == "Other"]),
    })

df_pairs = (pd.DataFrame(pair_rows)
              .sort_values("Total Exchange Flux", ascending=False))

# ============================================================
# SHEET S4: Per-metabolite exchange statistics
# ============================================================
met_rows = []
for met_id, group in df.groupby("metabolite_id"):
    met_rows.append({
        "Metabolite ID (BiGG)":    met_id,
        "Metabolite Name":         group["metabolite_name"].iloc[0],
        "Category":                group["category"].iloc[0],
        "Total Exchange Flux":     round(group["exchange_flux"].sum(), 4),
        "N Interactions":          len(group),
        "Unique Producers":        group["producer"].nunique(),
        "Unique Consumers":        group["consumer"].nunique(),
        "Top Producer":            (
            group.sort_values("flux_producer", ascending=False)["producer"].iloc[0]
        ),
        "Top Consumer":            (
            group.sort_values("flux_consumer", ascending=False)["consumer"].iloc[0]
        ),
        "Max Relative Flux (%)":   round(group["significance_pct"].max(), 4),
    })

df_mets = (pd.DataFrame(met_rows)
             .sort_values("Total Exchange Flux", ascending=False))

# ============================================================
# Write all sheets to a single Excel file
# ============================================================
out_path = f"{BASE}/supplementary_table_syncom.xlsx"

with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
    df_summary.to_excel(writer,      sheet_name="S1_Genome_Summary",     index=False)
    df_interactions.to_excel(writer, sheet_name="S2_All_Interactions",    index=False)
    df_pairs.to_excel(writer,        sheet_name="S3_Pairwise_Summary",    index=False)
    df_mets.to_excel(writer,         sheet_name="S4_Metabolite_Summary",  index=False)

print(f"Saved: {out_path}")
print(f"\nSheets generated:")
print(f"  S1_Genome_Summary      — {len(df_summary)} genomes")
print(f"  S2_All_Interactions    — {len(df_interactions)} interactions")
print(f"  S3_Pairwise_Summary    — {len(df_pairs)} producer–consumer pairs")
print(f"  S4_Metabolite_Summary  — {len(df_mets)} unique metabolites")

# Console preview of genome summary
print("\n=== GENOME SUMMARY PREVIEW ===")
cols_preview = [
    "Genome", "Compatibility Score", "Compatible (threshold=0.35)",
    "Net Contribution (mmol/gDW/h)",
    "Metabolites Exported (unique)", "Metabolites Imported (unique)"
]
print(df_summary[cols_preview].to_string(index=False))
